import { assert, assertEquals } from "@std/assert";
import nameJa from "../data/name-ja.json" with { type: "json" };
import nameOverrides from "../data/name-overrides.json" with { type: "json" };
import citiesData from "../data/cities.json" with { type: "json" };

// data/europe_*.geojson（全 20 年代）と data/hre_*.geojson（4 年代）の全 feature の
// NAME / SUBJECTO のユニーク値（null 除外）に data/rivers.geojson の全 feature の
// name のユニーク値（null 除外）を加えたリスト（勢力名 + 河川名）。
//
// TASK-47: 元々は data/name-overrides.json の renames 値・data/cities.json の
// 都市名（TASK-27）もこの静的リストに含めていたが、これらは自己参照問題
// （実データを更新してもリスト更新を忘れると検出できない）を持っていた。
// data/name-overrides.json・data/cities.json は拡張子が .json のため
// `with { type: "json" }` の静的 import で `deno test`（CI は --allow-read
// なしで実行）でも実データを読み取れる（動作確認済み）。そのためこの 2
// ソースは下記テストで実データ突合に切り替え、このリストからは除外した。
//
// 一方 data/europe_*.geojson・data/hre_*.geojson・data/rivers.geojson は拡張子が
// .geojson のため、Deno は `type: "json"` 属性を付けても
// "Expected a Json module, but identified a Unknown module" として拒否する
// （拡張子ベースの media type 判定によるもので、権限の有無とは無関係の
// 技術的制約。動作確認済み）。CI の `deno test` に --allow-read も付与されて
// いない（.github/workflows/ci.yml 参照）ため Deno.readFile 経由でも読めず、
// geojson 由来分は実データ突合が実現不可能。このリストとして静的に列挙し、
// データ変更時は下記コマンドで再生成して手動更新する運用とする。
//
// 再生成コマンド（リポジトリルートで実行）:
//   python3 -c "import json,glob; s=set(); [s.update(v for f2 in [json.load(open(f))] for ft in f2['features'] for k in ('NAME','SUBJECTO') if (v:=ft['properties'].get(k))) for f in glob.glob('data/europe_*.geojson')+glob.glob('data/hre_*.geojson')]; s.update(v for ft in json.load(open('data/rivers.geojson'))['features'] if (v:=ft['properties'].get('name'))); print(json.dumps(sorted(s),ensure_ascii=False,indent=2))"
const STATIC_GEOJSON_AND_RIVER_NAMES: string[] = [
  "3",
  "Abbasid Caliphate",
  "Abdelouadides",
  "Afghanistan",
  "Aghlabid Emirate",
  "Alans",
  "Albania",
  "Algeria",
  "Algeria (FR)",
  "Algiers",
  "Almohad Caliphate",
  "Almoravid dynasty",
  "Amu  Darya",
  "Angevin Empire",
  "Anhalt",
  "Arabia",
  "Arabia (Nejd)",
  "Arabs",
  "Aragón",
  "Archbishopric of Cologne",
  "Archbishopric of Mainz",
  "Archbishopric of Salzburg",
  "Archbishopric of Trier",
  "Archduchy of Austria",
  "Armenia",
  "Arran",
  "Artsakh",
  "Astrakhan Khanate",
  "Asturias",
  "Austria",
  "Austria Hungary",
  "Austrian Empire",
  "Austrian Netherlands",
  "Austro-Hungarian Empire",
  "Avars",
  "Azerbaijan",
  "Baden",
  "Baltic Tribes",
  "Baltic tribes",
  "Batavian Republic",
  "Bavaria",
  "Belgium",
  "Beylik of Aydin",
  "Blue Horde",
  "Bokhara Khanate",
  "Borcea",
  "Bosnia",
  "Bosnia-Herzegovina",
  "Brandenburg",
  "Bratul Chillia",
  "Bratul Sfintu Gheorghe",
  "Bratul Sulina",
  "Bremen",
  "Britany",
  "Brunswick",
  "Bulgar Khanate",
  "Bulgaria",
  "Bulgars",
  "Burgandy",
  "Buwayhid Emirates",
  "Byzantine Empire",
  "Caliphate of Córdoba",
  "Carolingian Empire",
  "Castile",
  "Castilla",
  "Castille",
  "Celtic kingdoms",
  "Chelmia",
  "Chuds",
  "Comté de Toulouse",
  "Corsica",
  "Crimean Khanate",
  "Croatia",
  "Croatian kingdom",
  "Cuman Khanates",
  "Cuman-Kipchak confederation",
  "Cuxhaven",
  "Cyprus",
  "Danes",
  "Danube",
  "Daugava",
  "Denmark",
  "Denmark-Norway",
  "Derbent",
  "Dnipro",
  "Duchy of Bavaria",
  "Duchy of Saxony",
  "Duchy of Swabia",
  "Duchy of Württemberg",
  "Durdzuks",
  "Dutch Republic",
  "Dutchy of Benevento",
  "East Francia",
  "Ebro",
  "Elbe",
  "Electoral Hesse",
  "Electorate of Bavaria",
  "Electorate of Brandenburg",
  "Electorate of Saxony",
  "Electorate of the Palatinate",
  "Emirate of Córdoba",
  "Emirate of Sicily",
  "Emirate of Tiflis",
  "Emirate of the White Sheep Turks",
  "England",
  "England and Ireland",
  "English territory",
  "Essex",
  "Euphrates",
  "Fatimid Caliphate",
  "Finland",
  "Finnmark",
  "Finno-Ugric taiga hunter-gatherers",
  "Fivizzano",
  "Florence",
  "France",
  "Franche-Comté",
  "Geneva",
  "Genoa",
  "Georgia",
  "German Empire",
  "Germany",
  "Ghaznavid Emirate",
  "Goghtn",
  "Golden Horde",
  "Granada",
  "Grand Duchy of Hesse",
  "Grand Duchy of Moscow",
  "Great Moravia",
  "Greece",
  "Greenland",
  "Habsburg Austria",
  "Habsburg Netherlands",
  "Hafsid Caliphate",
  "Hamburg",
  "Hanover",
  "Helvetic Republic",
  "Hohenzollern",
  "Holstein",
  "Holy Roman Empire",
  "Hungary",
  "Iceland",
  "Icelandic Commonwealth",
  "Idrisid Caliphate",
  "Ilkhanate",
  "Imperial Hungary",
  "Irlanda",
  "Italy",
  "Kakheti-Hereti",
  "Kalmar Union",
  "Kara Khitai Khaganate",
  "Karakalpaks",
  "Karelians",
  "Karkhanids",
  "Kazan Khanate",
  "Kent",
  "Khanate of the Golden Horde",
  "Khazars",
  "Khiva Khanate",
  "Khundzi",
  "Kievan Rus",
  "Kimek-Kipchak khaganate",
  "Kingdom of Bohemia",
  "Kingdom of France",
  "Kingdom of Georgia",
  "Kingdom of Hungary",
  "Kingdom of Ireland",
  "Kingdom of Norway",
  "Kingdom of Sardinia",
  "Kingdom of the Two Sicilies",
  "Kingfom of Italy",
  "Kurs",
  "Kyivan Rus",
  "Landgraviate of Hesse",
  "Landgraviate of Hesse-Darmstadt",
  "Landgraviate of Hesse-Kassel",
  "Lek",
  "Leks",
  "León",
  "Lippe-Detmold",
  "Lithuania",
  "Loire",
  "Lombard duchies",
  "Lombardy",
  "Lucca",
  "Luxembourg",
  "Lübeck",
  "Magyars",
  "Malta",
  "Mamluke Sultanate",
  "Maskat",
  "Massa",
  "Mecklenburg-Schwerin",
  "Mecklenburg-Strelitz",
  "Mercia",
  "Merinides",
  "Milan",
  "Milano (Austria)",
  "Modena",
  "Moldova",
  "Mongol Empire",
  "Montenegro",
  "Morocco",
  "Naples",
  "Nassau",
  "Navarre",
  "Nederrijn",
  "Netherlands",
  "Neva",
  "Nogai Horde",
  "Norway",
  "Nothumbria",
  "Novgorod",
  "Novgorod-Seversky",
  "Oder",
  "Oghuz",
  "Oghuz Turks",
  "Oldenburg",
  "Other Rus Principalities",
  "Ottoman Empire",
  "Palatinate",
  "Paleo-Siberian hunter-gatherers",
  "Papal States",
  "Parma",
  "Pechenegs",
  "Pechora",
  "Persia",
  "Peshemegs",
  "Picts",
  "Poland",
  "Poland-Lithuania",
  "Poland-Llituania",
  "Polish–Lithuanian Commonwealth",
  "Polyanians",
  "Pomerania",
  "Pontremoli",
  "Portugal",
  "Principality of Galicia-Volhynia",
  "Principality of Kyiv",
  "Principality of Novgorod",
  "Principality of Polotsk",
  "Principality of Vladimir-Suzdal",
  "Principality of Wallachia",
  "Prussia",
  "Prussians",
  "Pskov",
  "Quazaq Khanate",
  "Raška",
  "Republic of Kraków",
  "Republic of the Seven Zenden",
  "Rhine",
  "Romania",
  "Russia",
  "Russian Empire",
  "Ryazan",
  "Safavid Empire",
  "Saffarids",
  "Samanid Empire",
  "Sami",
  "Samis",
  "San Marino",
  "Sardinia",
  "Sardinia-Piedmont",
  "Savoy",
  "Savoy-Piedmont",
  "Saxony",
  "Schaumburg-Lippe",
  "Schleswig",
  "Scotland",
  "Scots",
  "Scottalnd",
  "Scottland",
  "Seine",
  "Seljuk Caliphate",
  "Seljuk Empire",
  "Serbia",
  "Severnaya Dvina",
  "Shirvan",
  "Siberians",
  "Sicily",
  "Slavic tribes",
  "Spain",
  "Spanish Habsburg",
  "Spanish Morocco",
  "Sukhona",
  "Suom",
  "Suomi",
  "Svir’",
  "Swabia",
  "Sweden",
  "Sweden–Norway",
  "Swedes and Goths",
  "Swiss Confederation",
  "Switzerland",
  "Syunik",
  "Sámi",
  "Tajo",
  "Tashir",
  "Tejo",
  "Teutonic Knights",
  "Thule",
  "Thuringia",
  "Tigris",
  "Timurid Emirates",
  "Timurid Empire",
  "Trebizond",
  "Tsardom of Muscovy",
  "Tunis",
  "Tunisia",
  "Turan",
  "Tuscany",
  "UK",
  "United Kingdom",
  "United Kingdom of Great Britain and Ireland",
  "United Kingdom of Netherlands",
  "Ural",
  "Venetia",
  "Venice",
  "Vistula",
  "Volga",
  "Volga Bulgars",
  "Vychegda",
  "Waal",
  "Waldeck",
  "Watassid Morocco",
  "Wattasid Caliphate",
  "Welsh",
  "Wessex",
  "West Francia",
  "Wetzlar",
  "White Horde",
  "Württemberg",
  "Zayyanid Caliphate",
  "central Asian khanates",
];

const mapping = nameJa as Record<string, string>;

Deno.test("name-ja.json はフラットな Record<string, string> で値は全て非空文字列", () => {
  assert(typeof nameJa === "object" && nameJa !== null);
  assert(!Array.isArray(nameJa));
  const entries = Object.entries(mapping);
  assert(entries.length > 0);
  for (const [key, value] of entries) {
    assert(key.length > 0, "空のキーが存在する");
    assertEquals(
      typeof value,
      "string",
      `値が文字列でない: ${key} -> ${JSON.stringify(value)}`,
    );
    assert(value.length > 0, `値が空文字列: ${key}`);
  }
});

Deno.test("主要国の日本語表記が期待どおり", () => {
  const expected: Record<string, string> = {
    "Holy Roman Empire": "神聖ローマ帝国",
    "France": "フランス",
    "Kingdom of France": "フランス王国",
    "England": "イングランド王国",
    "Castile": "カスティーリャ王国",
    "Ottoman Empire": "オスマン帝国",
    "Byzantine Empire": "ビザンツ帝国",
    "Teutonic Knights": "ドイツ騎士団領",
    "Papal States": "教皇領",
    "Venice": "ヴェネツィア共和国",
    "Golden Horde": "キプチャク・ハン国（ジョチ・ウルス）",
    "Grand Duchy of Moscow": "モスクワ大公国",
    "Kalmar Union": "カルマル同盟",
    "Austria": "オーストリア",
    // HRE 領邦は正式称号付きで統一（TASK-32）
    "Kingdom of Bohemia": "ボヘミア王国",
    "Electorate of Saxony": "ザクセン選帝侯領",
    "Duchy of Saxony": "ザクセン公領",
    "Electorate of Brandenburg": "ブランデンブルク選帝侯領",
    "Electorate of the Palatinate": "プファルツ選帝侯領",
    "Archbishopric of Mainz": "マインツ大司教領",
    "Archduchy of Austria": "オーストリア大公領",
    "Duchy of Bavaria": "バイエルン公領",
    "Electorate of Bavaria": "バイエルン選帝侯領",
  };
  for (const [name, ja] of Object.entries(expected)) {
    assertEquals(mapping[name], ja, `${name} の訳が期待と異なる`);
  }
});

/**
 * data/name-ja.json のキーとして期待される名前の全体集合を実データから組み立てる。
 * - 勢力名 + 河川名（data/europe_*.geojson・data/hre_*.geojson・
 *   data/rivers.geojson 由来）: 拡張子 .geojson は静的 import 不可（上記コメント
 *   参照）なため STATIC_GEOJSON_AND_RIVER_NAMES の静的リストを使う。
 * - renames 正規化後名・都市名（data/name-overrides.json・data/cities.json 由来）:
 *   拡張子 .json は静的 import 可能なため実データを直接読み、リストの
 *   自己参照問題（データ更新時の更新漏れを検出できない）を解消する。
 */
function expectedNames(): Set<string> {
  const names = new Set(STATIC_GEOJSON_AND_RIVER_NAMES);
  const overrides = nameOverrides as { renames: Record<string, string> };
  for (const renamed of Object.values(overrides.renames)) names.add(renamed);
  const cities = citiesData as { years: Record<string, { name: string }[]> };
  for (const entries of Object.values(cities.years)) {
    for (const entry of entries) names.add(entry.name);
  }
  return names;
}

Deno.test("全ユニーク NAME / SUBJECTO と renames 正規化後名・都市名を 100% カバーする", () => {
  const expected = expectedNames();
  const missing = [...expected].filter((name) => !(name in mapping));
  assertEquals(
    missing,
    [],
    `未登録の名前が ${missing.length} 件ある（カバレッジ 100% が必須）`,
  );
});

Deno.test("name-ja.json にデータ由来でない孤立キーが存在しない", () => {
  const expected = expectedNames();
  const orphans = Object.keys(mapping).filter((key) => !expected.has(key));
  assertEquals(
    orphans,
    [],
    "geojson / renames / cities に存在しないキーがある",
  );
});
