import { assert, assertEquals } from "@std/assert";
import nameJa from "../data/name-ja.json" with { type: "json" };

// data/europe_*.geojson（全 20 年代）と data/hre_*.geojson（4 年代）の全 feature の
// NAME / SUBJECTO のユニーク値（null 除外）に、data/rivers.geojson の全 feature の
// name のユニーク値（null 除外）、data/name-overrides.json の renames の
// 値側（正規化後名）、data/cities.json の全年代の都市 name（TASK-27）を加えた
// リスト。CI の `deno test` は権限なしで実行されるため geojson / json を実行時に
// 読まず、ここに列挙して検証する。
// データ変更時の再生成コマンド（リポジトリルートで実行）:
//   python3 -c "import json,glob; s=set(); [s.update(v for f2 in [json.load(open(f))] for ft in f2['features'] for k in ('NAME','SUBJECTO') if (v:=ft['properties'].get(k))) for f in glob.glob('data/europe_*.geojson')+glob.glob('data/hre_*.geojson')]; s.update(v for ft in json.load(open('data/rivers.geojson'))['features'] if (v:=ft['properties'].get('name'))); s.update(json.load(open('data/name-overrides.json'))['renames'].values()); s.update(c['name'] for cs in json.load(open('data/cities.json'))['years'].values() for c in cs); print(json.dumps(sorted(s),ensure_ascii=False,indent=2))"
const EXPECTED_NAMES: string[] = [
  "3",
  "Abbasid Caliphate",
  "Abdelouadides",
  "Afghanistan",
  "Aghlabid Emirate",
  "Al Furat",
  "Alans",
  "Albania",
  "Aleppo",
  "Algeria",
  "Algeria (FR)",
  "Algiers",
  "Almeria",
  "Almohad Caliphate",
  "Almoravid dynasty",
  "Amalfi",
  "Amsterdam",
  "Amu  Darya",
  "Angevin Empire",
  "Anhalt",
  "Ani",
  "Antioch",
  "Antwerp",
  "Arabia",
  "Arabia (Nejd)",
  "Arabs",
  "Aragón",
  "Armenia",
  "Arran",
  "Artsakh",
  "Astrakhan",
  "Astrakhan Khanate",
  "Asturias",
  "Austria",
  "Austria Hungary",
  "Austrian Empire",
  "Austrian Netherlands",
  "Austro-Hungarian Empire",
  "Avars",
  "Azerbaijan",
  "Baden",
  "Baltic Tribes",
  "Baltic tribes",
  "Barcelona",
  "Batavian Republic",
  "Bavaria",
  "Bejaia",
  "Belgium",
  "Berlin",
  "Beylik of Aydin",
  "Birmingham",
  "Blue Horde",
  "Bobastro",
  "Bohemia",
  "Bokhara Khanate",
  "Bologna",
  "Borcea",
  "Bosnia",
  "Bosnia-Herzegovina",
  "Brandenburg",
  "Bratul Chillia",
  "Bratul Sfintu Gheorghe",
  "Bratul Sulina",
  "Bremen",
  "Britany",
  "Bruges",
  "Brunswick",
  "Brussels",
  "Budapest",
  "Bulgar Khanate",
  "Bulgaria",
  "Bulgars",
  "Burgandy",
  "Burgos",
  "Bursa",
  "Buwayhid Emirates",
  "Byzantine Empire",
  "Caliphate of Córdoba",
  "Carolingian Empire",
  "Cartagena",
  "Castile",
  "Castilla",
  "Castille",
  "Celtic kingdoms",
  "Chelmia",
  "Chuds",
  "Cologne",
  "Comté de Toulouse",
  "Constantinople",
  "Cordoba",
  "Corsica",
  "Crimean Khanate",
  "Croatia",
  "Croatian kingdom",
  "Cuman Khanates",
  "Cuman-Kipchak confederation",
  "Cuxhaven",
  "Cyprus",
  "Danes",
  "Danube",
  "Daugava",
  "Denmark",
  "Denmark-Norway",
  "Derbent",
  "Dicle",
  "Diyarbakir",
  "Dnepre",
  "Dnipro",
  "Donau",
  "Dresden",
  "Dublin",
  "Ducal Saxony",
  "Duchy of Swabia",
  "Durdzuks",
  "Dutch Republic",
  "Dutchy of Benevento",
  "East Francia",
  "Ebro",
  "Edessa",
  "Edinburgh",
  "Edirne",
  "Elbe",
  "Electoral Hesse",
  "Electoral Saxony",
  "Emirate of Córdoba",
  "Emirate of Sicily",
  "Emirate of Tiflis",
  "Emirate of the White Sheep Turks",
  "England",
  "England and Ireland",
  "English territory",
  "Essex",
  "Euphrates",
  "Fatimid Caliphate",
  "Feodosia",
  "Fez",
  "Finland",
  "Finnmark",
  "Finno-Ugric taiga hunter-gatherers",
  "Firat",
  "Fivizzano",
  "Florence",
  "France",
  "Franche-Comté",
  "Gdansk",
  "Geneva",
  "Genoa",
  "Georgia",
  "German Empire",
  "Germany",
  "Ghaznavid Emirate",
  "Ghent",
  "Glasgow",
  "Gliwice",
  "Goghtn",
  "Golden Horde",
  "Granada",
  "Grand Duchy of Hesse",
  "Grand Duchy of Moscow",
  "Great Moravia",
  "Greece",
  "Greenland",
  "Habsburg Austria",
  "Habsburg Netherlands",
  "Hafsid Caliphate",
  "Hamburg",
  "Hanover",
  "Helvetic Republic",
  "Hesse",
  "Hesse-Darmstadt",
  "Hesse-Kassel",
  "Hohenzollern",
  "Holstein",
  "Holy Roman Empire",
  "Hungary",
  "Iceland",
  "Icelandic Commonwealth",
  "Idrisid Caliphate",
  "Ilkhanate",
  "Imperial Hungary",
  "Irlanda",
  "Italy",
  "Kairouan",
  "Kakheti-Hereti",
  "Kalaa",
  "Kalmar Union",
  "Kara Khitai Khaganate",
  "Karakalpaks",
  "Karaman",
  "Karelians",
  "Karkhanids",
  "Katowice",
  "Kayseri",
  "Kazan Khanate",
  "Kent",
  "Khanate of the Golden Horde",
  "Khazars",
  "Khiva Khanate",
  "Khundzi",
  "Kiev",
  "Kievan Rus",
  "Kimek-Kipchak khaganate",
  "Kingdom of France",
  "Kingdom of Georgia",
  "Kingdom of Hungary",
  "Kingdom of Ireland",
  "Kingdom of Norway",
  "Kingdom of Sardinia",
  "Kingdom of the Two Sicilies",
  "Kingfom of Italy",
  "Konya",
  "Kurs",
  "Kyivan Rus",
  "Lek",
  "Leks",
  "León",
  "Lippe-Detmold",
  "Lisbon",
  "Lithuania",
  "Liverpool",
  "Loire",
  "Lombard duchies",
  "Lombardy",
  "London",
  "Lucca",
  "Luxembourg",
  "Lyon",
  "Lübeck",
  "Madrid",
  "Magyars",
  "Mainz",
  "Malta",
  "Mamluke Sultanate",
  "Manchester",
  "Mashhad",
  "Maskat",
  "Massa",
  "Mecklenburg-Schwerin",
  "Mecklenburg-Strelitz",
  "Mercia",
  "Merida",
  "Merinides",
  "Metz",
  "Milan",
  "Milano (Austria)",
  "Modena",
  "Moldova",
  "Mongol Empire",
  "Montenegro",
  "Morocco",
  "Moscow",
  "Mosul",
  "Munich",
  "Naples",
  "Nassau",
  "Navarre",
  "Nederrijn",
  "Netherlands",
  "Neva",
  "Newcastle upon Tyne",
  "Nishapur",
  "Nogai Horde",
  "Norway",
  "Nothumbria",
  "Novgorod",
  "Novgorod-Seversky",
  "Oder",
  "Odessa",
  "Oghuz",
  "Oghuz Turks",
  "Ohrid",
  "Oldenburg",
  "Other Rus Principalities",
  "Ottoman Empire",
  "Palatinate",
  "Paleo-Siberian hunter-gatherers",
  "Palermo",
  "Papal States",
  "Paris",
  "Parma",
  "Pavia",
  "Pechenegs",
  "Pechora",
  "Persia",
  "Peshemegs",
  "Picts",
  "Poland",
  "Poland-Lithuania",
  "Poland-Llituania",
  "Polish–Lithuanian Commonwealth",
  "Polyanians",
  "Pomerania",
  "Pontremoli",
  "Portugal",
  "Prague",
  "Preslav",
  "Principality of Galicia-Volhynia",
  "Principality of Kyiv",
  "Principality of Novgorod",
  "Principality of Polotsk",
  "Principality of Vladimir-Suzdal",
  "Principality of Wallachia",
  "Prussia",
  "Prussians",
  "Pskov",
  "Qazvin",
  "Qom",
  "Quazaq Khanate",
  "Rabat",
  "Rayy",
  "Raška",
  "Reggio di Calabria",
  "Republic of Kraków",
  "Republic of the Seven Zenden",
  "Rhein",
  "Rhin",
  "Rhine",
  "Rhondda",
  "Romania",
  "Rome",
  "Rotterdam",
  "Rouen",
  "Russia",
  "Russian Empire",
  "Ryazan",
  "Safavid Empire",
  "Saffarids",
  "Saint Petersburg",
  "Salerno",
  "Salzburg",
  "Samanid Empire",
  "Samarra",
  "Sami",
  "Samis",
  "San Marino",
  "Sarai",
  "Sardinia",
  "Sardinia-Piedmont",
  "Savoy",
  "Savoy-Piedmont",
  "Saxony",
  "Schaumburg-Lippe",
  "Schleswig",
  "Scotland",
  "Scots",
  "Scottalnd",
  "Scottland",
  "Seine",
  "Seljuk Caliphate",
  "Seljuk Empire",
  "Serbia",
  "Severnaya Dvina",
  "Seville",
  "Shirvan",
  "Siberians",
  "Sicily",
  "Sivas",
  "Slavic tribes",
  "Smyrna",
  "Soltaniyeh",
  "Spain",
  "Spanish Habsburg",
  "Spanish Morocco",
  "Sukhona",
  "Suom",
  "Suomi",
  "Svir’",
  "Swabia",
  "Sweden",
  "Sweden–Norway",
  "Swedes and Goths",
  "Swiss Confederation",
  "Switzerland",
  "Syunik",
  "Sámi",
  "Tabriz",
  "Tajo",
  "Targoviste",
  "Tarsus",
  "Tashir",
  "Tbilisi",
  "Tejo",
  "Teutonic Knights",
  "Thessaloniki",
  "Thule",
  "Thuringia",
  "Tigris",
  "Timurid Emirates",
  "Timurid Empire",
  "Tlemcen",
  "Trabzon",
  "Trebizond",
  "Trier",
  "Tsardom of Muscovy",
  "Tunis",
  "Tunisia",
  "Turan",
  "Tuscany",
  "UK",
  "United Kingdom",
  "United Kingdom of Great Britain and Ireland",
  "United Kingdom of Netherlands",
  "Ural",
  "Venetia",
  "Venice",
  "Vienna",
  "Vistula",
  "Volga",
  "Volga Bulgars",
  "Vychegda",
  "Waal",
  "Waldeck",
  "Warsaw",
  "Watassid Morocco",
  "Wattasid Caliphate",
  "Welsh",
  "Wessex",
  "West Francia",
  "Wetzlar",
  "White Horde",
  "Württemberg",
  "Zayyanid Caliphate",
  "central Asian khanates",
];

const mapping = nameJa as Record<string, string>;

Deno.test("name-ja.json はフラットな Record<string, string> で値は全て非空文字列", () => {
  assert(typeof nameJa === "object" && nameJa !== null);
  assert(!Array.isArray(nameJa));
  const entries = Object.entries(mapping);
  assert(entries.length > 0);
  for (const [key, value] of entries) {
    assert(key.length > 0, "空のキーが存在する");
    assertEquals(
      typeof value,
      "string",
      `値が文字列でない: ${key} -> ${JSON.stringify(value)}`,
    );
    assert(value.length > 0, `値が空文字列: ${key}`);
  }
});

Deno.test("主要国の日本語表記が期待どおり", () => {
  const expected: Record<string, string> = {
    "Holy Roman Empire": "神聖ローマ帝国",
    "France": "フランス",
    "Kingdom of France": "フランス王国",
    "England": "イングランド王国",
    "Castile": "カスティーリャ王国",
    "Ottoman Empire": "オスマン帝国",
    "Byzantine Empire": "ビザンツ帝国",
    "Teutonic Knights": "ドイツ騎士団領",
    "Papal States": "教皇領",
    "Venice": "ヴェネツィア共和国",
    "Golden Horde": "キプチャク・ハン国（ジョチ・ウルス）",
    "Grand Duchy of Moscow": "モスクワ大公国",
    "Kalmar Union": "カルマル同盟",
    "Austria": "オーストリア",
    "Bohemia": "ボヘミア",
    "Electoral Saxony": "ザクセン選帝侯領",
  };
  for (const [name, ja] of Object.entries(expected)) {
    assertEquals(mapping[name], ja, `${name} の訳が期待と異なる`);
  }
});

Deno.test("全ユニーク NAME / SUBJECTO と renames 正規化後名を 100% カバーする", () => {
  const missing = EXPECTED_NAMES.filter((name) => !(name in mapping));
  assertEquals(
    missing,
    [],
    `未登録の名前が ${missing.length} 件ある（カバレッジ 100% が必須）`,
  );
});

Deno.test("name-ja.json にデータ由来でない孤立キーが存在しない", () => {
  const expected = new Set(EXPECTED_NAMES);
  const orphans = Object.keys(mapping).filter((key) => !expected.has(key));
  assertEquals(orphans, [], "geojson / renames に存在しないキーがある");
});
